COLUNAS_TEMPORADA = "Periodo"
COLUNAS_JOGO = "Codigo_temporada_jogo, Data_jogo, Codigo_time_mandante, Codigo_time_visitante, Pontuacao_time_mandante, Pontuacao_time_visitante"
COLUNAS_EQUIPE = "Nome"
COLUNAS_JOGADOR = "Codigo_equipe_atual, idade, Nome"
COLUNAS_INFORMACOES_JOGO_JOGADOR = "Codigo_jogador_fk, Codigo_jogo_fk, Tempo_em_quadra, Arremessos, Arremessos_certos, Tres_pontos, Tres_pontos_certos, Lance_livre, Lance_livre_certos, Rebotes_ofensivos, Rebotes_defensivos, Assistencias, Roubos, Bloqueios, Bolas_perdidas, Faltas, Pontos, Contribuicao"