TIMES = {
    "Atlanta Hawks":"ATL",
    "Boston Celtics": "BOS",
    "Brooklyn Nets": "BRK",
    "New York Knicks": "NYK",
    "Philadelphia 76ers": "PHI",
    "Toronto Raptors": "TOR",
    "Chicago Bulls": "CHI",
    "Minnesota Timberwolves": "",
    "Houston Rockets":"HOU",
    "Orlando Magic":"ORL",
    "Detroit Pistons":"DET",
    "Cleveland Cavaliers": "CLE",
    "Indiana Pacers":"IND",
    "Milwaukee Bucks": "MIL",
    "Denver Nuggets": "DEN",
    "Oklahoma City Thunder": "OKC",
    "Portland Trail Blazers": "POR",
    "Utah Jazz": "UTA",
    "Golden State Warriors": "GSW",
    "LA Clippers": "LAC",
    "Los Angeles Lakers": "LAL",
    "Phoenix Suns": "PHO",
    "Sacramento Kings": "SAC",
    "Charlotte Hornets": "CHO",
    "Miami Heat": "MIA",
    "Washington Wizards": "WAS",
    "Dallas Mavericks": "DAL",
    "Memphis Grizzlies": "MEM",
    "New Orleans Pelicans": "NOP",
    "San Antonio Spurs": "SAS"
}