GAME_COLUMNS = {   "MP": "mp", "FG": "fg", "FGA": "fga", 
                   "3P": "three_p", "3PA": "three_pa", "FT":"ft", "FTA": "fta",
                   "ORB": "ofr", "DRB":"dfr", "AST": "ast", "STL": "stl", 
                   "BLK": "blk", "TOV": "tov", "PF": "pf", "PTS": "pts", "+/-": "plus_minus"}
TEAMS = {
    "Atlanta Hawks":"ATL",
    "Boston Celtics": "BOS",
    "Brooklyn Nets": "BRK",
    "New York Knicks": "NYK",
    "Philadelphia 76ers": "PHI",
    "Toronto Raptors": "TOR",
    "Chicago Bulls": "CHI",
    "Minnesota Timberwolves": "MIN",
    "Houston Rockets":"HOU",
    "Orlando Magic":"ORL",
    "Detroit Pistons":"DET",
    "Cleveland Cavaliers": "CLE",
    "Indiana Pacers":"IND",
    "Milwaukee Bucks": "MIL",
    "Denver Nuggets": "DEN",
    "Oklahoma City Thunder": "OKC",
    "Portland Trail Blazers": "POR",
    "Utah Jazz": "UTA",
    "Golden State Warriors": "GSW",
    "Los Angeles Clippers": "LAC",
    "Los Angeles Lakers": "LAL",
    "Phoenix Suns": "PHO",
    "Sacramento Kings": "SAC",
    "Charlotte Hornets": "CHO",
    "Miami Heat": "MIA",
    "Washington Wizards": "WAS",
    "Dallas Mavericks": "DAL",
    "Memphis Grizzlies": "MEM",
    "New Orleans Pelicans": "NOP",
    "San Antonio Spurs": "SAS"
}